### ISSUE TITLE
Update composer dependencies for a php 7.2+ future version

### ISSUE THREAD

**Issue by rotexdegba** [rotexsoft/versatile-collections#13]
- For PHP 7.2+ versions of this library, get rid of the dependency on **paragonie/random_compat** , since random_int() is available in PHP 7
  - **paragonie/random_compat** is currently being used as a PHP 5.6 polyfill for random_int() in VersatileCollections\random_array_key
- Update **sebastian/exporter** to a version that supports strictly php 7+ (e.g 3.1.X).

**Comment by robertfausk** [comment]
Any updates on this?
I'm currently stuck with incompatible "sebastian/exporter (locked at 3.1.0)" version.

**Comment by rotexdegba** [comment]
Been a bit busy lately. I will create a branch for a php 7.2+ version of the package and update the dependencies ASAP (hopefully by this weekend).

**Comment by rotexdegba** [comment]
Just released version **2.1.1** of this package. The incompatibility should be resolved now. Try cutting out all the required dependencies in the require section of your project's composer.json file and then run composer update to remove all installed dependencies in your project and then paste back all the dependencies and then run composer update again, that should fix it.

**Comment by rotexdegba** [comment]
@robertfausk did the fix work for you?

**Comment by robertfausk** [comment]
> @robertfausk did the fix work for you?

It works like a charm!

**Comment by rotexdegba** [comment]
> > @robertfausk did the fix work for you?
> 
> It works like a charm!

Thanks for the feedback!!

**Comment by rotexdegba** [comment]
Created a 2.X branch for PHP 5.6+. Master branch is now supporting only PHP 7.2+ moving forward and the composer.json dependencies have been updated accordingly.  **paragonie/random_compat** is no longer required and **sebastian/exporter** 3.1+ is now being required.
